### PR TITLE
Reopen Saved + Quality of Life changes + Bugfixes

### PR DESCRIPTION
**Pull request by isaacy13**
- users can now reopen saved Arbalest Test Results (.atr files; nothing but a sqlite database file)
- QoL: opening a file that is already open now just switches to the correct tab (as opposed to creating two instances)
- QoL: user is prompted to either open or discard previous test results
- QoL: user can update filepath of .g file (stored inside of .atr file); e.g.: if .g file was moved, renamed, deleted
- bugfix: opening multiple untitled files no longer crashes app
- bugfix: database is now properly closed (no hanging connections / queries)

### CODE REVIEW

**Comment by isaacy13** [comment]
bug: new untitled files will crash

**Comment by isaacy13** [comment]
bug: results duplicate on opening previous results
- steps to reproduce: open shipping_container.g, run tests, close tab, re-open .g file and choose to open .atr file

**Comment by isaacy13** [comment]
bug: pressing 'cancel' on open/discard results prompt makes program think no .atr file
- steps to reproduce: open .g file that has an associated .atr file, click cancel, try to build tests -> it says "must save this file before running tests"

**Comment by isaacy13** [comment]
note: 4a6080266ad67e43d26ac8965ea95fe051978dcd has bad commit message
- this commit actually fixed duplicate results bug

**Comment by isaacy13** [comment]
bug: can open multiple of the same .g file, doing so >= 3 times will cause crash

**Comment by isaacy13** [comment]
note: there is a "bug" that doesn't display the test results if certain tests aren't clicked
- this is because other parsers haven't been merged yet; upon their merge, these test results should display

**Review by daperego — APPROVED** [review]

**Pull request merged**
